#!/usr/bin/env bash

this_script_dir=$(dirname "$0")

ext=.json

schemas_dir="$this_script_dir/../_schemas"
types_dir="$this_script_dir/../_types"

mkdir -p "$types_dir"
rm $types_dir/*.d.ts

echo schemas_dir=$schemas_dir
echo types_dir=$types_dir

(
#  cd $schemas_dir # || echo "Error cd to $schemas_dir" && exit 1

  for pathname in ./$schemas_dir/*$ext; do
    filename1=$(basename $pathname $ext)

    source="$filename1$ext"
    target="$types_dir/$filename1.d.ts"
    temp="temp"

    echo -e "$source \t -> \t $target"

    json2ts -i "$schemas_dir/$source" -o "$target" --cwd $schemas_dir
#    --unreachableDefinitions
#     --no-declareExternallyReferenced

    echo -e "/**\n* Source file:  \"$source\"\n* Location:     \"$(pwd)\"\n* Generated by: \"$0\"\n* Date:         \"$(date -Is)\" \n*/\n"  | cat - "$target" > $temp && mv $temp "$target"
    
  done
)

echo "* FINISHED"
