/**
* Source file:  "SuccessResponse.json"
* Location:     "/home/alykoshin/projects/dev/npm/@utilities/packages/net"
* Generated by: "src/jsonrpc/_utils/build.sh"
* Date:         "2020-09-14T13:37:19+03:00" 
*/

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This member is REQUIRED on success.
 * This member MUST NOT exist if there was an error invoking the method.
 * The value of this member is determined by the method invoked on the Server.
 */
export type SuccessResult = unknown;

export interface SuccessResponse {
  /**
   * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
   */
  jsonrpc: string;
  result: SuccessResult;
  /**
   * This member is REQUIRED.
   * It MUST be the same as the value of the id member in the Request Object.
   * If there was an error in detecting the id in the Request object (e.g. Parse error/Invalid Request), it MUST be Null.
   */
  id: string | number | null;
}
