language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "node"
  - "stable"
before_install:
script: "npm run-script test-travis"
# Send coverage data to Coveralls
before_script:
after_script: "npm run-script coverall"
